### ISSUE TITLE
Custom options not showing on productdetailpage

### ISSUE THREAD

**Issue by assaka** [dmitrykazak/magento2-custom-option-default-value#1]
I have installed the extension and the checkbox is_default is showing in the Customizable Options tab, but the custom options are not showing on the productdetailpage.
I am using Magento 2.3.4

**Comment by ktopouzi** [comment]
Hey @assaka I am having the exact same issue. Did you find any workarounds?

**Comment by ktopouzi** [comment]
@dmitrykazak I got the same issue as described here but every time I save the product the checkbox resets.  Any ideas?
